//! The EKS add-on catalog served by `DescribeAddonVersions`, the default
//! version `CreateAddon` installs, and the recommended pod-identity
//! configuration `DescribeAddonConfiguration` returns.
//!
//! The catalog is not hand-written: `addon_catalog.json` is generated by
//! `scripts/generate-eks-addon-catalog.py` from a daily capture of the real
//! `aws eks describe-addon-versions` output, pinned to the same date as the
//! `DescribeClusterVersions` table (see `CLUSTER_VERSIONS_AS_OF` in
//! `eks_helpers.rs`). Every version string, architecture, compute type,
//! compatibility and `defaultVersion` flag is what AWS returned that day.

use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::{json, Value};

use fakecloud_aws::arn::Arn;

const CATALOG_JSON: &str = include_str!("addon_catalog.json");

#[derive(Deserialize)]
struct CatalogFile {
    addons: Vec<AddonEntry>,
}

/// One `AddonInfo`, as AWS returns it.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct AddonEntry {
    addon_name: String,
    #[serde(rename = "type")]
    addon_type: String,
    owner: String,
    publisher: String,
    default_namespace: String,
    /// `productId` / `productUrl` for AWS Marketplace listings.
    #[serde(default)]
    marketplace_information: Option<Value>,
    /// Newest first, the order AWS lists them in.
    addon_versions: Vec<AddonVersionEntry>,
}

/// One `AddonVersionInfo`.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct AddonVersionEntry {
    addon_version: String,
    architecture: Vec<String>,
    compute_types: Vec<String>,
    compatibilities: Vec<CompatibilityEntry>,
    requires_configuration: bool,
    requires_iam_permissions: bool,
}

/// One `Compatibility`: the version runs on `cluster_version`, and
/// `default_version` marks it as the one EKS installs there by default.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CompatibilityEntry {
    cluster_version: String,
    platform_versions: Vec<String>,
    default_version: bool,
}

fn catalog() -> &'static [AddonEntry] {
    static CATALOG: OnceLock<Vec<AddonEntry>> = OnceLock::new();
    CATALOG
        .get_or_init(|| {
            let parsed: CatalogFile = serde_json::from_str(CATALOG_JSON)
                .expect("embedded EKS add-on catalog must be valid JSON");
            parsed.addons
        })
        .as_slice()
}

/// The add-on catalog returned by `DescribeAddonVersions`, one `AddonInfo` per
/// add-on. With a `kubernetesVersion` only the versions compatible with it are
/// listed, each with just that cluster version's compatibility (an unknown
/// cluster version yields no add-ons, as on AWS); without one every version
/// and every compatibility is listed.
pub(crate) fn addon_catalog(cluster_version: Option<&str>) -> Vec<Value> {
    catalog()
        .iter()
        .filter_map(|addon| {
            let versions: Vec<Value> = addon
                .addon_versions
                .iter()
                .filter_map(|ver| {
                    let compatibilities: Vec<Value> = ver
                        .compatibilities
                        .iter()
                        .filter(|c| cluster_version.is_none_or(|cv| c.cluster_version == cv))
                        .map(|c| {
                            json!({
                                "clusterVersion": c.cluster_version,
                                "platformVersions": c.platform_versions,
                                "defaultVersion": c.default_version,
                            })
                        })
                        .collect();
                    if compatibilities.is_empty() {
                        return None;
                    }
                    Some(json!({
                        "addonVersion": ver.addon_version,
                        "architecture": ver.architecture,
                        "computeTypes": ver.compute_types,
                        "compatibilities": compatibilities,
                        "requiresConfiguration": ver.requires_configuration,
                        "requiresIamPermissions": ver.requires_iam_permissions,
                    }))
                })
                .collect();
            if versions.is_empty() {
                return None;
            }
            let mut info = json!({
                "addonName": addon.addon_name,
                "type": addon.addon_type,
                "addonVersions": versions,
                "publisher": addon.publisher,
                "owner": addon.owner,
                "defaultNamespace": addon.default_namespace,
            });
            if let Some(mp) = &addon.marketplace_information {
                info["marketplaceInformation"] = mp.clone();
            }
            Some(info)
        })
        .collect()
}

/// The version flagged `defaultVersion` for `addon_name` on `cluster_version`.
fn catalog_default(addon_name: &str, cluster_version: &str) -> Option<&'static str> {
    catalog()
        .iter()
        .find(|a| a.addon_name == addon_name)?
        .addon_versions
        .iter()
        .find(|ver| {
            ver.compatibilities
                .iter()
                .any(|c| c.cluster_version == cluster_version && c.default_version)
        })
        .map(|ver| ver.addon_version.as_str())
}

/// Why an add-on version can't be installed on a cluster. Both surface as
/// `InvalidParameterException` with the message EKS returns (captured from a
/// live 1.37 cluster).
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum AddonVersionError {
    /// The add-on is unknown or has no build for the cluster's Kubernetes
    /// version. EKS reports this even when a version was requested.
    #[error("Addon {addon} specified is not supported in {cluster_version} kubernetes version")]
    AddonNotSupported {
        addon: String,
        cluster_version: String,
    },
    /// The requested `addonVersion` is not offered for the cluster's
    /// Kubernetes version.
    #[error("Addon version specified is not supported")]
    VersionNotSupported,
}

/// The version `CreateAddon` / `UpdateAddon` (and CloudFormation's
/// `AWS::EKS::Addon`) install for `addon_name` on a cluster running
/// `cluster_version`, as EKS resolves it:
///
/// - an add-on that is not in the catalog, or has no build for that
///   Kubernetes minor, is `AddonNotSupported`, whether or not a version was
///   requested (EKS checks this first);
/// - no `requested` version: the catalog version flagged `defaultVersion` for
///   that minor;
/// - a `requested` version: accepted only when the catalog lists it as
///   compatible with that minor, else `VersionNotSupported` (also for version
///   strings that don't exist at all).
///
/// The catalog holds every add-on AWS listed, AWS Marketplace ones included,
/// so an unknown name is refused the way EKS refuses it. Marketplace
/// subscriptions are not modeled: a listed Marketplace add-on installs.
pub fn resolve_addon_version(
    addon_name: &str,
    cluster_version: &str,
    requested: Option<&str>,
) -> Result<String, AddonVersionError> {
    let not_supported = || AddonVersionError::AddonNotSupported {
        addon: addon_name.to_string(),
        cluster_version: cluster_version.to_string(),
    };
    let addon = catalog()
        .iter()
        .find(|a| a.addon_name == addon_name)
        .ok_or_else(not_supported)?;
    let compatible = |ver: &&AddonVersionEntry| {
        ver.compatibilities
            .iter()
            .any(|c| c.cluster_version == cluster_version)
    };
    if !addon.addon_versions.iter().any(|ver| compatible(&ver)) {
        return Err(not_supported());
    }
    match requested {
        Some(v) => addon
            .addon_versions
            .iter()
            .filter(compatible)
            .find(|ver| ver.addon_version == v)
            .map(|ver| ver.addon_version.clone())
            .ok_or(AddonVersionError::VersionNotSupported),
        None => catalog_default(addon_name, cluster_version)
            .map(str::to_string)
            .ok_or_else(not_supported),
    }
}

/// The recommended pod-identity configuration for an add-on, returned by
/// `DescribeAddonConfiguration` as `podIdentityConfiguration`: the service
/// account the add-on runs as and the AWS-managed policies EKS suggests for it
/// (the EKS user guide's AWS add-on and community add-on pages). Add-ons that
/// need no AWS permissions, or that document only IRSA setup, have none.
pub(crate) fn pod_identity_configuration(region: &str, addon_name: &str) -> Value {
    let policy =
        |name: &str| Arn::global_in(region, "iam", "aws", &format!("policy/{name}")).to_string();
    let config = |service_account: &str, policies: &[&str]| {
        let policies: Vec<String> = policies.iter().map(|p| policy(p)).collect();
        json!([{
            "serviceAccount": service_account,
            "recommendedManagedPolicies": policies,
        }])
    };
    match addon_name {
        "vpc-cni" => config("aws-node", &["AmazonEKS_CNI_Policy"]),
        // `AmazonEBSCSIDriverPolicyV2` was only created in April 2026, after
        // the catalog snapshot, so the original service-role policy applies.
        "aws-ebs-csi-driver" => config(
            "ebs-csi-controller-sa",
            &["service-role/AmazonEBSCSIDriverPolicy"],
        ),
        "aws-efs-csi-driver" => config(
            "efs-csi-controller-sa",
            &["service-role/AmazonEFSCSIDriverPolicy"],
        ),
        "aws-fsx-csi-driver" => config("fsx-csi-controller-sa", &["AmazonFSxFullAccess"]),
        "amazon-cloudwatch-observability" => config(
            "cloudwatch-agent",
            &["CloudWatchAgentServerPolicy", "AWSXrayWriteOnlyAccess"],
        ),
        "aws-network-flow-monitoring-agent" => config(
            "aws-network-flow-monitor-agent-service-account",
            &["CloudWatchNetworkFlowMonitorAgentPublishPolicy"],
        ),
        "aws-privateca-connector-for-kubernetes" => config(
            "aws-privateca-issuer",
            &["AWSPrivateCAConnectorForKubernetesPolicy"],
        ),
        "amazon-sagemaker-hyperpod-training-operator" => config(
            "hp-training-operator-controller-manager",
            &["AmazonSageMakerHyperPodTrainingOperatorAccess"],
        ),
        "external-dns" => config("external-dns", &["AmazonRoute53FullAccess"]),
        _ => json!([]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn versions_on(addon_name: &str, cluster_version: &str) -> Vec<String> {
        let addons = addon_catalog(Some(cluster_version));
        let addon = addons
            .iter()
            .find(|a| a["addonName"] == addon_name)
            .unwrap_or_else(|| panic!("{addon_name} missing on {cluster_version}"));
        addon["addonVersions"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v["addonVersion"].as_str().unwrap().to_string())
            .collect()
    }

    #[test]
    fn embedded_catalog_parses_and_covers_the_snapshot_addons() {
        let names: Vec<&str> = catalog().iter().map(|a| a.addon_name.as_str()).collect();
        for want in [
            "vpc-cni",
            "coredns",
            "kube-proxy",
            "aws-ebs-csi-driver",
            "aws-secrets-store-csi-driver-provider",
            "aws-privateca-connector-for-kubernetes",
            "sriov-network-metrics-exporter",
            "amazon-sagemaker-hyperpod-taskgovernance",
            "amazon-sagemaker-hyperpod-observability",
            "amazon-sagemaker-hyperpod-training-operator",
            "amazon-sagemaker-spaces",
            "fluent-bit",
            "external-dns",
        ] {
            assert!(names.contains(&want), "missing {want}");
        }
        // Released after the snapshot date, so not in the catalog.
        assert!(!names.contains(&"aws-ec2-local-instance-store-csi-driver"));
        // AWS-owned, EKS community and AWS Marketplace listings; only the
        // Marketplace ones carry marketplaceInformation.
        assert!(catalog()
            .iter()
            .all(|a| matches!(a.owner.as_str(), "aws" | "community" | "aws-marketplace")));
        assert!(catalog()
            .iter()
            .all(|a| (a.owner == "aws-marketplace") == a.marketplace_information.is_some()));
    }

    #[test]
    fn kube_proxy_lists_the_real_per_minor_builds() {
        for (cv, latest) in [
            ("1.30", "v1.30.14-eksbuild.18"),
            ("1.31", "v1.31.13-eksbuild.2"),
            ("1.32", "v1.32.9-eksbuild.2"),
            ("1.33", "v1.33.5-eksbuild.2"),
            ("1.34", "v1.34.1-eksbuild.2"),
        ] {
            assert_eq!(versions_on("kube-proxy", cv)[0], latest, "{cv}");
        }
        // The generated `v<minor>.0-eksbuild.2` line never existed for 1.31.
        assert!(!versions_on("kube-proxy", "1.31").contains(&"v1.31.0-eksbuild.3".to_string()));
        assert_eq!(
            resolve_addon_version("kube-proxy", "1.34", None).unwrap(),
            "v1.34.0-eksbuild.2"
        );
    }

    #[test]
    fn coredns_tracks_the_minor_with_v1_12_4_on_newest() {
        for cv in ["1.33", "1.34"] {
            assert_eq!(versions_on("coredns", cv)[0], "v1.12.4-eksbuild.1");
        }
        assert_eq!(versions_on("coredns", "1.28")[0], "v1.10.1-eksbuild.38");
        assert_eq!(
            resolve_addon_version("coredns", "1.34", None).unwrap(),
            "v1.12.3-eksbuild.1"
        );
        assert_eq!(
            resolve_addon_version("coredns", "1.33", None).unwrap(),
            "v1.12.1-eksbuild.2"
        );
    }

    #[test]
    fn vpc_cni_is_ec2_only_with_real_default() {
        let addons = addon_catalog(Some("1.32"));
        let cni = addons.iter().find(|a| a["addonName"] == "vpc-cni").unwrap();
        for v in cni["addonVersions"].as_array().unwrap() {
            assert_eq!(v["computeTypes"], json!(["ec2"]));
        }
        assert_eq!(
            resolve_addon_version("vpc-cni", "1.32", None).unwrap(),
            "v1.20.4-eksbuild.2"
        );
    }

    #[test]
    fn mountpoint_is_published_by_s3() {
        let addons = addon_catalog(None);
        let mp = addons
            .iter()
            .find(|a| a["addonName"] == "aws-mountpoint-s3-csi-driver")
            .unwrap();
        assert_eq!(mp["publisher"], "s3");
        assert_eq!(mp["owner"], "aws");
    }

    #[test]
    fn scoping_to_a_cluster_version_keeps_only_its_compatibility() {
        for addon in addon_catalog(Some("1.29")) {
            for ver in addon["addonVersions"].as_array().unwrap() {
                let compat = ver["compatibilities"].as_array().unwrap();
                assert_eq!(compat.len(), 1);
                assert_eq!(compat[0]["clusterVersion"], "1.29");
            }
        }
        assert!(addon_catalog(Some("1.27")).is_empty());
    }

    #[test]
    fn addon_without_a_build_for_the_minor_is_not_supported() {
        // adot has no 1.34 build in the snapshot: no fallback to another
        // minor's default, EKS refuses the add-on.
        assert!(versions_on_opt("adot", "1.34").is_none());
        let adot_err = AddonVersionError::AddonNotSupported {
            addon: "adot".to_string(),
            cluster_version: "1.34".to_string(),
        };
        let adot_on_134 = Err(adot_err.clone());
        assert_eq!(resolve_addon_version("adot", "1.34", None), adot_on_134);
        // Checked before the requested version, even a real adot build.
        assert_eq!(
            resolve_addon_version("adot", "1.34", Some("v0.131.0-eksbuild.1")),
            adot_on_134
        );
        assert_eq!(
            resolve_addon_version("adot", "1.33", None).as_deref(),
            Ok("v0.131.0-eksbuild.1")
        );
        // A minor EKS does not offer has no builds of anything.
        assert!(matches!(
            resolve_addon_version("vpc-cni", "1.18", None),
            Err(AddonVersionError::AddonNotSupported { .. })
        ));
        // EKS's wording, from a live 1.37 cluster.
        assert_eq!(
            adot_err.to_string(),
            "Addon adot specified is not supported in 1.34 kubernetes version"
        );
    }

    #[test]
    fn requested_version_must_be_compatible_with_the_minor() {
        // A real build for another minor (kube-proxy skew) is refused.
        assert_eq!(
            resolve_addon_version("kube-proxy", "1.31", Some("v1.32.9-eksbuild.2")),
            Err(AddonVersionError::VersionNotSupported)
        );
        // A string that never existed is refused.
        assert_eq!(
            resolve_addon_version("kube-proxy", "1.31", Some("v1.31.0-eksbuild.3")),
            Err(AddonVersionError::VersionNotSupported)
        );
        assert_eq!(
            resolve_addon_version("kube-proxy", "1.31", Some("v1.31.13-eksbuild.2")).as_deref(),
            Ok("v1.31.13-eksbuild.2")
        );
        assert_eq!(
            AddonVersionError::VersionNotSupported.to_string(),
            "Addon version specified is not supported"
        );
        // A malformed version string gets the same answer.
        assert_eq!(
            resolve_addon_version("kube-proxy", "1.31", Some("not-a-version")),
            Err(AddonVersionError::VersionNotSupported)
        );
    }

    #[test]
    fn unknown_addons_are_refused_and_marketplace_listings_install() {
        for requested in [None, Some("v9.9.9")] {
            assert_eq!(
                resolve_addon_version("not-an-addon", "1.31", requested)
                    .unwrap_err()
                    .to_string(),
                "Addon not-an-addon specified is not supported in 1.31 kubernetes version"
            );
        }
        // Marketplace add-ons are in the catalog, with their listing.
        let akuity = addon_catalog(Some("1.31"))
            .into_iter()
            .find(|a| a["addonName"] == "akuity_agent")
            .expect("akuity_agent listed for 1.31");
        assert_eq!(akuity["owner"], "aws-marketplace");
        assert!(akuity["marketplaceInformation"]["productUrl"]
            .as_str()
            .unwrap()
            .contains("marketplace"));
        assert!(resolve_addon_version("akuity_agent", "1.31", None).is_ok());
        // AWS-owned add-ons carry no marketplaceInformation.
        let vpc_cni = addon_catalog(Some("1.31"))
            .into_iter()
            .find(|a| a["addonName"] == "vpc-cni")
            .unwrap();
        assert!(vpc_cni.get("marketplaceInformation").is_none());
    }

    fn versions_on_opt(addon_name: &str, cluster_version: &str) -> Option<Vec<Value>> {
        addon_catalog(Some(cluster_version))
            .into_iter()
            .find(|a| a["addonName"] == addon_name)
            .map(|a| a["addonVersions"].as_array().unwrap().clone())
    }

    #[test]
    fn catalog_cluster_versions_match_describe_cluster_versions() {
        let offered: Vec<String> = crate::eks_helpers::cluster_version_catalog("eks")
            .iter()
            .map(|v| v["clusterVersion"].as_str().unwrap().to_string())
            .collect();
        for addon in catalog() {
            for ver in &addon.addon_versions {
                for c in &ver.compatibilities {
                    assert!(
                        offered.contains(&c.cluster_version),
                        "{} {} lists {}",
                        addon.addon_name,
                        ver.addon_version,
                        c.cluster_version
                    );
                }
            }
        }
        // Every offered version has the core networking add-ons with a default.
        for cv in &offered {
            for name in ["vpc-cni", "coredns", "kube-proxy"] {
                assert!(catalog_default(name, cv).is_some(), "{name} on {cv}");
            }
        }
    }

    #[test]
    fn pod_identity_configuration_matches_the_eks_docs() {
        let cfg = pod_identity_configuration("us-east-1", "external-dns");
        assert_eq!(cfg[0]["serviceAccount"], "external-dns");
        assert_eq!(
            cfg[0]["recommendedManagedPolicies"],
            json!(["arn:aws:iam::aws:policy/AmazonRoute53FullAccess"])
        );
        let cfg = pod_identity_configuration("us-east-1", "aws-ebs-csi-driver");
        assert_eq!(
            cfg[0]["recommendedManagedPolicies"],
            json!(["arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"])
        );
        let cfg = pod_identity_configuration("us-east-1", "aws-privateca-connector-for-kubernetes");
        assert_eq!(cfg[0]["serviceAccount"], "aws-privateca-issuer");
        let cfg = pod_identity_configuration("cn-north-1", "external-dns");
        assert_eq!(
            cfg[0]["recommendedManagedPolicies"][0],
            "arn:aws-cn:iam::aws:policy/AmazonRoute53FullAccess"
        );
        assert_eq!(
            pod_identity_configuration("us-east-1", "coredns"),
            json!([])
        );
    }
}
