#!/usr/bin/env python3
"""Regenerate the JSON-protocol pagination tables (`src/pagination_gen.rs`).

For each service below, reads its Smithy model(s) and records every operation
whose input models a page token: where the token and page size travel (an
`@httpQuery` name or a JSON body member), which output list a page slices, the
output token member, whether that member is `@required`, and the error the
operation declares for a token it did not mint. The tables feed
`fakecloud_core::pagination::{validate_json_page, apply_json_page}`, which each
service applies at its dispatch boundary. Run after refreshing a model:

    python3 scripts/generate-json-pagination-tables.py
"""
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# crate -> [(const name, model file)]
SERVICES = {
    "fakecloud-opensearch": [("ES_PAGED_OPS", "es.json"), ("OPENSEARCH_PAGED_OPS", "opensearch.json")],
    "fakecloud-xray": [("PAGED_OPS", "xray.json")],
    "fakecloud-appsync": [("PAGED_OPS", "appsync.json")],
    "fakecloud-apigatewayv2": [("PAGED_OPS", "apigatewayv2.json")],
    "fakecloud-apigateway": [("PAGED_OPS", "apigateway.json")],
}
TOKEN_NAMES = ("NextToken", "nextToken", "position")
SIZE_NAMES = ("MaxResults", "maxResults", "limit")
# Declared errors that mean "this token is not one I handed out", most
# specific first.
TOKEN_ERRORS = (
    "InvalidPaginationTokenException",
    "InvalidNextTokenException",
    "ValidationException",
    "InvalidRequestException",
    "BadRequestException",
)


def json_name(member_name, member):
    return member.get("traits", {}).get("smithy.api#jsonName", member_name)


def location(member_name, member):
    traits = member.get("traits", {})
    if "smithy.api#httpQuery" in traits:
        return f'PageLoc::Query("{traits["smithy.api#httpQuery"]}")'
    return f'PageLoc::Body("{json_name(member_name, member)}")'


def rows_for(model_file):
    shapes = json.load(open(os.path.join(REPO, "aws-models", model_file)))["shapes"]
    rows, skipped = [], []
    for sid, shape in sorted(shapes.items()):
        if shape.get("type") != "operation":
            continue
        op = sid.split("#")[1]
        inp = shapes.get(shape.get("input", {}).get("target", ""), {}).get("members", {})
        out = shapes.get(shape.get("output", {}).get("target", ""), {}).get("members", {})
        tok_in = next((n for n in TOKEN_NAMES if n in inp), None)
        if not tok_in:
            continue
        tok_out = next((n for n in TOKEN_NAMES if n in out), None)
        if not tok_out:
            skipped.append(f"{op} (no output token)")
            continue
        pg = shape.get("traits", {}).get("smithy.api#paginated") or {}
        lists = [n for n, m in out.items() if shapes.get(m["target"], {}).get("type") == "list"]
        items = pg.get("items") if pg.get("items") in lists else None
        if items is None:
            if len(lists) != 1:
                skipped.append(f"{op} (result lists: {lists or 'none'})")
                continue
            items = lists[0]
        size = next((n for n in SIZE_NAMES if n in inp), None)
        errors = [e["target"].split("#")[1] for e in shape.get("errors", [])]
        bad = next((e for e in TOKEN_ERRORS if e in errors), None)
        rows.append(
            (
                op,
                location(tok_in, inp[tok_in]),
                location(size, inp[size]) if size else None,
                json_name(items, out[items]),
                json_name(tok_out, out[tok_out]),
                "smithy.api#required" in out[tok_out].get("traits", {}),
                bad,
            )
        )
    return rows, skipped


def main():
    for crate, tables in SERVICES.items():
        out_path = os.path.join(REPO, "crates", crate, "src", "pagination_gen.rs")
        lines = [
            "// @generated by scripts/generate-json-pagination-tables.py from the",
            "// service's aws-models. Do not edit by hand; rerun after a model refresh.",
            "",
            "use fakecloud_core::pagination::{JsonPagedOp, PageLoc};",
            "",
        ]
        for const, model in tables:
            rows, skipped = rows_for(model)
            lines.append(f"/// Every paginated operation in `aws-models/{model}`.")
            for s in skipped:
                lines.append(f"/// Not sliceable as a list: {s}.")
            lines.append(f"pub(crate) const {const}: &[JsonPagedOp] = &[")
            for op, tok, size, items, tok_out, required, bad in rows:
                size_s = f"Some({size})" if size else "None"
                bad_s = f'Some("{bad}")' if bad else "None"
                lines.append(
                    f'    JsonPagedOp {{ action: "{op}", token: {tok}, size: {size_s}, '
                    f'items: "{items}", next_token: "{tok_out}", '
                    f"next_token_required: {str(required).lower()}, bad_token: {bad_s} }},"
                )
            lines += ["];", ""]
            print(f"{crate}: {len(rows)} ops from {model}" + (f", skipped {skipped}" if skipped else ""))
        open(out_path, "w").write("\n".join(lines))
        subprocess.run(["rustfmt", "--edition", "2021", out_path], check=True)


if __name__ == "__main__":
    sys.exit(main())
