#!/usr/bin/env python3
"""Regenerate crates/fakecloud-ec2/src/pagination_table.rs from aws-models/ec2.json.

Every EC2 operation whose input models `NextToken` is paginated. The table
records, per operation, the result set element(s) a page slices and the
`@range` the model puts on `MaxResults`, so the shared pagination layer in
`crates/fakecloud-ec2/src/pagination.rs` can page every one of them the same
way. Run after refreshing aws-models/ec2.json:

    python3 scripts/generate-ec2-pagination-table.py
"""
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = os.path.join(REPO, "aws-models", "ec2.json")
OUT = os.path.join(REPO, "crates", "fakecloud-ec2", "src", "pagination_table.rs")

# Results that carry more than one list. `concat` pages the lists as one
# sequence in the order given (a page fills from the first list, then the
# next); `parallel` lists are index-aligned views of the same items and are
# sliced with the same window.
MULTI = {
    "DescribeVpcEndpointServices": ("Parallel", ["ServiceNames", "ServiceDetails"]),
    "GetSubnetCidrReservations": (
        "Concat",
        ["SubnetIpv4CidrReservations", "SubnetIpv6CidrReservations"],
    ),
    # The associations are the paged items; the tag set describes the checks.
    "DescribeApplicationStatusCheckAssociations": ("Concat", ["Associations"]),
}


def xml_name(member_name, member):
    return member.get("traits", {}).get("smithy.api#xmlName") or (
        member_name[0].lower() + member_name[1:]
    )


def main():
    shapes = json.load(open(MODEL))["shapes"]
    rows = []
    for sid, shape in sorted(shapes.items()):
        if shape.get("type") != "operation":
            continue
        op = sid.split("#")[1]
        inp = shapes.get(shape.get("input", {}).get("target", ""), {})
        out = shapes.get(shape.get("output", {}).get("target", ""), {})
        im = inp.get("members", {})
        om = out.get("members", {})
        if "NextToken" not in im:
            continue
        rng = None
        mr = im.get("MaxResults")
        if mr:
            target = shapes.get(mr["target"], {})
            r = mr.get("traits", {}).get("smithy.api#range") or target.get(
                "traits", {}
            ).get("smithy.api#range")
            if r:
                rng = (r.get("min"), r.get("max"))
        if op in MULTI:
            mode, members = MULTI[op]
        else:
            mode = "Concat"
            pg = shape.get("traits", {}).get("smithy.api#paginated") or {}
            if pg.get("items"):
                members = [pg["items"]]
            else:
                members = [
                    n
                    for n, m in om.items()
                    if shapes.get(m["target"], {}).get("type") == "list"
                ]
            if len(members) > 1:
                sys.exit(f"{op}: several result lists {members}; add it to MULTI")
        sets = [xml_name(n, om[n]) for n in members]
        rows.append((op, mode, sets, rng))

    lines = [
        "// @generated by scripts/generate-ec2-pagination-table.py from",
        "// aws-models/ec2.json. Do not edit by hand; rerun the script after a model",
        "// refresh.",
        "",
        "use crate::pagination::{PagedOp, SetLayout};",
        "",
        "/// Every EC2 operation whose input models `NextToken`, sorted by name.",
        "pub(crate) const PAGED_OPS: &[PagedOp] = &[",
    ]
    for op, mode, sets, rng in rows:
        sets_s = ", ".join(f'"{s}"' for s in sets)
        if rng:
            lo = "i64::MIN" if rng[0] is None else int(rng[0])
            hi = "i64::MAX" if rng[1] is None else int(rng[1])
            rng_s = f"Some(({lo}, {hi}))"
        else:
            rng_s = "None"
        lines.append(
            f'    PagedOp {{ action: "{op}", sets: &[{sets_s}], layout: SetLayout::{mode}, max_results: {rng_s} }},'
        )
    lines.append("];")
    lines.append("")
    open(OUT, "w").write("\n".join(lines))
    subprocess.run(["rustfmt", "--edition", "2021", OUT], check=True)
    print(f"wrote {len(rows)} operations to {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
