#!/usr/bin/env python3
"""Regenerate crates/fakecloud-opensearch/src/pagination_gen.rs.

Reads aws-models/opensearch.json and aws-models/es.json and records, for every
operation whose input models a `NextToken`, where the token and page size
travel (an `@httpQuery` name or a JSON body member), which output list a page
slices, the output token member, and the error the operation declares for a
token it did not mint. Run after refreshing either model:

    python3 scripts/generate-opensearch-pagination-table.py
"""
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "crates", "fakecloud-opensearch", "src", "pagination_gen.rs")
MODELS = [("Es", "es.json"), ("OpenSearch", "opensearch.json")]
TOKEN_NAMES = ("NextToken", "nextToken")
SIZE_NAMES = ("MaxResults", "maxResults")
# The output token is `@required` on a few list shapes; those send it empty on
# the last page instead of omitting it.
# Declared errors that mean "this token is not one I handed out", most
# specific first.
TOKEN_ERRORS = ("InvalidPaginationTokenException", "ValidationException")


def location(member_name, member):
    traits = member.get("traits", {})
    if "smithy.api#httpQuery" in traits:
        return f'Loc::Query("{traits["smithy.api#httpQuery"]}")'
    return f'Loc::Body("{traits.get("smithy.api#jsonName", member_name)}")'


def main():
    rows = []
    for api, fname in MODELS:
        shapes = json.load(open(os.path.join(REPO, "aws-models", fname)))["shapes"]
        for sid, shape in sorted(shapes.items()):
            if shape.get("type") != "operation":
                continue
            op = sid.split("#")[1]
            inp = shapes.get(shape.get("input", {}).get("target", ""), {}).get("members", {})
            out = shapes.get(shape.get("output", {}).get("target", ""), {}).get("members", {})
            tok_in = next((n for n in TOKEN_NAMES if n in inp), None)
            if not tok_in:
                continue
            tok_out = next((n for n in TOKEN_NAMES if n in out), None)
            if not tok_out:
                sys.exit(f"{api} {op}: no output token")
            size = next((n for n in SIZE_NAMES if n in inp), None)
            pg = shape.get("traits", {}).get("smithy.api#paginated") or {}
            if pg.get("items"):
                items = pg["items"]
            else:
                lists = [
                    n
                    for n, m in out.items()
                    if shapes.get(m["target"], {}).get("type") == "list"
                ]
                if len(lists) != 1:
                    sys.exit(f"{api} {op}: ambiguous result lists {lists}")
                items = lists[0]
            errors = [e["target"].split("#")[1] for e in shape.get("errors", [])]
            bad = next((e for e in TOKEN_ERRORS if e in errors), None)
            required = "smithy.api#required" in out[tok_out].get("traits", {})
            rows.append(
                (
                    api,
                    op,
                    location(tok_in, inp[tok_in]),
                    location(size, inp[size]) if size else None,
                    items,
                    tok_out,
                    bad,
                    required,
                )
            )

    lines = [
        "// @generated by scripts/generate-opensearch-pagination-table.py from",
        "// aws-models/es.json and aws-models/opensearch.json. Do not edit by hand.",
        "",
        "use crate::pagination::{Loc, PagedOp};",
        "use crate::service::Api;",
        "",
        "/// Every operation whose input models a `NextToken`.",
        "pub(crate) const PAGED_OPS: &[PagedOp] = &[",
    ]
    for api, op, tok, size, items, tok_out, bad, required in rows:
        size_s = f"Some({size})" if size else "None"
        bad_s = f'Some("{bad}")' if bad else "None"
        lines.append(
            f'    PagedOp {{ api: Api::{api}, action: "{op}", token: {tok}, size: {size_s}, '
            f'items: "{items}", next_token: "{tok_out}", next_token_required: {str(required).lower()}, '
            f'bad_token: {bad_s} }},'
        )
    lines += ["];", ""]
    open(OUT, "w").write("\n".join(lines))
    subprocess.run(["rustfmt", "--edition", "2021", OUT], check=True)
    print(f"wrote {len(rows)} operations to {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
